#!/usr/bin/env python
# ./dna_codes_3
# Decodes a DNA sequence using the process of compliment,
# transcription, and translation.
# The DNA is already split into triplets.
#
# By        : Leomar Durán <https://github.com/lduran2/>
# When      : 2021-05-13t05:01
# For       : KINS 1223
# Version   : 1.3
#
# Changelog :
#     v1.3 - 2021-05-13t05:01
#         read from the translations csv file
#
#     v1.2 - 2021-05-13t04:49
#         transcribing to mRNA
#
#     v1.1 - 2021-05-13t04:44
#         complimenting the DNA
#
#     v1.0 - 2021-05-13t04:26
#         start with splitting DNA by triplets by whitespaces

import csv # for DictReader

# complimentary bases in DNA
compliments = {
    'A': 'T',
    'G': 'C',
    'T': 'A',
    'C': 'G'
}

transcriptions = {
    'A': 'U',
    'G': 'C',
    'T': 'A',
    'C': 'G'
}

def main():
    # get the DNA sequence
    # split into list of characters including spaces
    dna = list(input('Enter the DNA.\n> '))

    # the complimentary bases, split into characters
    # only base characters
    dna_compliment = list(map(lambda c: compliments.get(c, ''), dna))

    # transcribe
    m_rna = list(map(lambda c: transcriptions.get(c, ''), dna_compliment))

    # read the translations file into the translations dictionary
    translations = {}   # the translations dictionary
    with open('translations.csv') as csvfile:
        csvin = csv.DictReader(csvfile)
        for row in csvin:
            translations[row['codon']] = row['amino_acid']
        # end for row in csvin
    # end with open('translations.csv') as csvfile

    # test the translations
    print(translations['AAA'])
    print(translations['UUG'])

    # print the results
    print('Complimentary DNA:', ''.join(dna_compliment))
    print('Transcription mRNA:', ''.join(m_rna))

main()
print('Done.')