#!/usr/bin/env python
# ./dna_codes_3
# Decodes a DNA sequence using the process of compliment,
# transcription, and translation.
# The DNA is already split into triplets.
#
# By        : Leomar Durán <https://github.com/lduran2/>
# When      : 2021-05-13t04:49
# For       : KINS 1223
# Version   : 1.1
#
# Changelog :
#     v1.1 - 2021-05-13t04:49
#         transcribing to mRNA
#
#     v1.1 - 2021-05-13t04:44
#         complimenting the DNA
#
#     v1.0 - 2021-05-13t04:26
#         start with splitting DNA by triplets by whitespaces

# complimentary bases in DNA
compliments = {
    'A': 'T',
    'G': 'C',
    'T': 'A',
    'C': 'G'
}

transcriptions = {
    'A': 'U',
    'G': 'C',
    'T': 'A',
    'C': 'G'
}

def main():
    # get the DNA sequence
    # split into list of characters including spaces
    dna = list(input('Enter the DNA.\n> '))

    # the complimentary bases, split into characters
    # only base characters
    dna_compliment = list(map(lambda c: compliments.get(c, ''), dna))

    # transcribe
    m_rna = list(map(lambda c: transcriptions.get(c, ''), dna_compliment))

    # print the results
    print('Complimentary DNA:', ''.join(dna_compliment))
    print('Transcription mRNA:', ''.join(m_rna))

main()
print('Done.')